Add configuration local app data support
pascaloon/FlashSearcher pull request #2
Opened 2020-08-07 20:24 UTC by NapOli1084

The SearchConfiguration.xml file and search indexes were saved directly
at the location of the executing assembly, which meant that different
configuration and indexes were used when we ran the GUI Viewer vs the
CLI application or when we ran Debug vs Release. It also meant data
files were saved along with the binaries.

The new behavior first checks if there is a configuration file at the
location of the executing assembly and uses it if that's the case. That
allows backward compatibility for users that have their configuration at
that location. However, if there is no configuration at that location,
we now look into `%LocalAppData%/FlashSearcher` and save the default
configuration there if there's isn't one already. That allows sharing a
single configuration between GUI/CLI and Debug/Release, and saves user
data in her/his own folder.

2020-08-07 21:48 UTC, pascaloon requested changes

2020-08-07 21:48 UTC, pascaloon commented on FlashSearch.Configuration/ConfigurationPathResolver.cs
> +                return ConfigFileName;
Why not throw?

2020-08-07 21:48 UTC, pascaloon commented on FlashSearch.Viewer/ViewModels/SearchViewModel.cs
> +            string indexDirectory = ConfigurationPathResolver.GetIndexDir(SelectedProject.Name, SelectedFileFilter.Index);
Could you refactor `ConfigurationPathResolver` into an injectable service? (like for the file service for example)
I'm not too fond of Singletons

2020-08-07 23:21 UTC, NapOli1084 commented on FlashSearch.Configuration/ConfigurationPathResolver.cs
> +                return ConfigFileName;
Because I didn't want that to prevent looking into app data folder. But I guess not finding the assembly path is not very likely anyway. If you prefer I can put back the throw.

2020-08-07 23:22 UTC, NapOli1084 commented on FlashSearch.Viewer/ViewModels/SearchViewModel.cs
> +            string indexDirectory = ConfigurationPathResolver.GetIndexDir(SelectedProject.Name, SelectedFileFilter.Index);
Ok, I'm not too familiar with injectable services, but I'll look at the file service.

2020-08-07 23:23 UTC, pascaloon commented on FlashSearch.Configuration/ConfigurationPathResolver.cs
> +                return ConfigFileName;
The only way I couldn't think where the location of an assembly is null is when it's loaded as a byte array.
I'd prefer a throw or return null.

2020-08-10 11:47 UTC, NapOli1084 commented on FlashSearch.Configuration/ConfigurationPathResolver.cs
> +                return ConfigFileName;
Ok, will do!

2020-08-17 18:37 UTC, pascaloon commented
Alright! Thanks for the MR ❤️ !

2020-08-17 18:38 UTC, merged